/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.0 public/models/Room-Baked.glb 
*/

import React, { useEffect } from 'react'
import { useGLTF, useTexture, useVideoTexture } from '@react-three/drei';
import * as THREE from "three";
import {motion} from "framer-motion-3d"
import { animate, useMotionValue, useAnimation} from 'framer-motion';
import { useFrame } from '@react-three/fiber';


export function Office(props) {

  const {section} = props;
  const { nodes, materials } = useGLTF('models/BK-Final3.glb')  
  // const { nodes, materials } = useGLTF('models/BK-Video.glb')  
  const texture = useTexture("textures/BK2-Final.jpg");
  const textureVSCode = useVideoTexture("textures/vscode.mp4");  
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 1
  })

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.42,
  })

  const textureOpacity = useMotionValue(0);
  const GlassTextureOpacity = useMotionValue(0);


 
    const controls_chair = useAnimation();
  
    useEffect(() => {
      if (section === 0) {
        controls_chair.start({
          rotateY: Math.PI,
          transition: { duration: 0.8} // 4 seconds
        });
  
        const timeout = setTimeout(() => {
          controls_chair.start({transition: { duration: 1 } }); // stops smoothly
        }, 1000); 
  
        return () => clearTimeout(timeout); // cleanup
      }
    }, []);


  return (
    <group {...props} dispose={null}>
      {/* <mesh name="screen_display" 
      geometry={nodes.screen_display.geometry}  
      position={[0.199, 1.1, -1.322]} 
      rotation={[0, -1.571, 0]} >
        <meshBasicMaterial map={textureVSCode} toneMapped={false} />
      </mesh>   */}
      <group name="Scene">
        {/* <group name="Empty" position={[0.256, 0.332, -0.32]} rotation={[-Math.PI, 0.1, -Math.PI]} scale={0.902}>
          <group name="Armature" position={[0.012, 0, 0.043]} rotation={[Math.PI / 2, 0, 0]}>
            <primitive object={nodes.Hips} />
            <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={textureMaterial} skeleton={nodes.Wolf3D_Body.skeleton} />
            <skinnedMesh name="Wolf3D_Glasses" geometry={nodes.Wolf3D_Glasses.geometry} material={textureMaterial} skeleton={nodes.Wolf3D_Glasses.skeleton} />
            <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={textureMaterial} skeleton={nodes.Wolf3D_Hair.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={textureMaterial} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={textureMaterial} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={textureMaterial} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
            <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={textureMaterial} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
            <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={textureMaterial} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={textureMaterial} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={textureMaterial} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
          </group>
        </group> */}
        <group name="Houseplant_1" position={[-1.19, 0.017, -1.326]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh name="Houseplant_1_1" geometry={nodes.Houseplant_1_1.geometry} material={textureMaterial} />
          <mesh name="Houseplant_1_2" geometry={nodes.Houseplant_1_2.geometry} material={textureMaterial} />
          <mesh name="Houseplant_1_3" geometry={nodes.Houseplant_1_3.geometry} material={textureMaterial} />
        </group>
        <group name="table" position={[0.259, 0.008, -1.213]} rotation={[0, -1.571, 0]}>
          <mesh name="Plane001_Plane002_BlackWood" geometry={nodes.Plane001_Plane002_BlackWood.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_BlackWood_1" geometry={nodes.Plane001_Plane002_BlackWood_1.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_BlackWood_2" geometry={nodes.Plane001_Plane002_BlackWood_2.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_BlackWood_3" geometry={nodes.Plane001_Plane002_BlackWood_3.geometry} material={textureMaterial} />
          <mesh name="Plane001_Plane002_BlackWood_4" geometry={nodes.Plane001_Plane002_BlackWood_4.geometry} material={textureMaterial} />
        </group>
        <mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={textureMaterial} position={[0.166, 0.969, -1.003]} scale={0.005} />
        <mesh name="Mousepad" geometry={nodes.Mousepad.geometry} material={textureMaterial} position={[0.502, 0.968, -0.937]} rotation={[-Math.PI / 2, 0, 0]} scale={[6.829, 8.313, 0.09]} />
        <mesh name="ComputerMouse_mesh" geometry={nodes.ComputerMouse_mesh.geometry} material={textureMaterial} position={[0.507, 0.969, -0.941]} rotation={[Math.PI, 0, Math.PI]} scale={0.02} />
        <group name="Phone" position={[1.014, 0.955, -0.914]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
          <mesh name="Phone_01_Cube037-Mesh" geometry={nodes['Phone_01_Cube037-Mesh'].geometry} material={textureMaterial} />
          <mesh name="Phone_01_Cube037-Mesh_1" geometry={nodes['Phone_01_Cube037-Mesh_1'].geometry} material={textureMaterial} />
          <mesh name="Phone_01_Cube037-Mesh_2" geometry={nodes['Phone_01_Cube037-Mesh_2'].geometry} material={textureMaterial} />
        </group>
        <group name="Small_Plant" position={[0.991, 1.14, -1.443]} scale={0.521}>
          <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
          <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={textureMaterial} />
          <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={textureMaterial} />
        </group>
        <group name="Mat" position={[0.595, 0, 0.577]} scale={0.742}>
          <mesh name="rugRectangle_3" geometry={nodes.rugRectangle_3.geometry} material={textureMaterial} />
          <mesh name="rugRectangle_3_1" geometry={nodes.rugRectangle_3_1.geometry} material={textureMaterial} />
        </group>
        <group name="Shelf" position={[0.136, 2.166, -1.583]} scale={0.243}>
          <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={textureMaterial} />
          <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={textureMaterial} />
        </group>
        <group name="Lamp" position={[-0.047, 2.355, -1.588]} scale={0.034}>
          <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={textureMaterial} />
          <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={textureMaterial} />
          <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={textureMaterial} />
        </group>
        <group name="pCube37" position={[0.927, 0.994, -0.617]} scale={0.001}>
          <mesh name="pCube37_1" geometry={nodes.pCube37_1.geometry} material={textureMaterial} />
          <mesh name="pCube37_1_1" geometry={nodes.pCube37_1_1.geometry} material={textureMaterial} />
          <mesh name="pCube37_1_2" geometry={nodes.pCube37_1_2.geometry} material={textureMaterial} />
          <mesh name="pCube37_1_3" geometry={nodes.pCube37_1_3.geometry} material={textureMaterial} />
          <mesh name="pCube37_1_4" geometry={nodes.pCube37_1_4.geometry} material={textureMaterial} />
          <mesh name="pCube37_1_5" geometry={nodes.pCube37_1_5.geometry} material={textureMaterial} />
          <mesh name="pCube37_1_6" geometry={nodes.pCube37_1_6.geometry} material={textureMaterial} />
        </group>
        <group name="screen" position={[0.199, 1.1, -1.322]} rotation={[0, -1.571, 0]}>
          <mesh name="mesh76221598" geometry={nodes.mesh76221598.geometry} material={textureMaterial} />
          <mesh name="mesh76221598_1" geometry={nodes.mesh76221598_1.geometry} material={textureMaterial} />
        </group>
        <group name="Digital_clock_Cube" position={[0.32, 2.321, -1.546]} scale={0.014}>
          <mesh name="Digital_clock_Cube-Mesh" geometry={nodes['Digital_clock_Cube-Mesh'].geometry} material={textureMaterial} />
          <mesh name="Digital_clock_Cube-Mesh_1" geometry={nodes['Digital_clock_Cube-Mesh_1'].geometry} material={textureMaterial} />
          <mesh name="Digital_clock_Cube-Mesh_2" geometry={nodes['Digital_clock_Cube-Mesh_2'].geometry} material={textureMaterial} />
          <mesh name="Digital_clock_Cube-Mesh_3" geometry={nodes['Digital_clock_Cube-Mesh_3'].geometry} material={textureMaterial} />
        </group>
        <group name="Chair" position={[0.265, 0.373, -0.337]} rotation={[-Math.PI, 0.013, -Math.PI]} scale={0.879}>
          <mesh name="mesh173738516" geometry={nodes.mesh173738516.geometry} material={textureMaterial} />
          <mesh name="mesh173738516_1" geometry={nodes.mesh173738516_1.geometry} material={textureMaterial} />
          <mesh name="mesh173738516_2" geometry={nodes.mesh173738516_2.geometry} material={textureMaterial} />
          <mesh name="mesh173738516_3" geometry={nodes.mesh173738516_3.geometry} material={textureMaterial} />
        </group>
        {/* <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={textureMaterial} position={[-0.085, 0.932, 0.343]} rotation={[Math.PI / 2, 0, -3.026]} scale={0.066} /> */}
        <group name="Plane">
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={textureMaterial} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={textureMaterial} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/sceen.glb')
